@auth_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYkBnbWFpbC5jb20iLCJpZCI6MiwiaWF0IjoxNzQxMDg1ODc5LCJleHAiOjE3NDExNzIyNzl9.zKo2bx8k0DBWDm_3sv8rGvoeeRvscDzLTFn5Htd1nSs
GET http://localhost:3001/api/blogs
Authorization: {{auth_token}}
###
GET http://localhost:3001/api/blogs?search=github
Authorization: {{auth_token}}
###
GET http://localhost:3001/api/authors
Authorization: {{auth_token}}
###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: {{auth_token}}

{
  "author": "Ismail Marghich",
  "url": "https://github.com/IsmailMarghich",
  "title": "My github page",
  "likes": 0,
  "year": 2025
}
###
DELETE http://localhost:3001/api/blogs/5
Authorization: {{auth_token}}

###
PUT http://localhost:3001/api/blogs/7
Content-Type: application/json
Authorization: {{auth_token}}

{
  "likes": 10
}
###error
PUT http://localhost:3001/api/blogs/7
Content-Type: application/json
Authorization: {{auth_token}}

{
    "likes": "d"
}
###