GET http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Ismail Marghich",
  "url": "https://github.com/IsmailMarghich",
  "title": "My github page",
  "likes": 0
}
###
DELETE http://localhost:3001/api/blogs/7

###
PUT http://localhost:3001/api/blogs/7
Content-Type: application/json

{
  "likes": 10
}
###error
PUT http://localhost:3001/api/blogs/7
Content-Type: application/json

{
    "likes": "d"
}
###